server:
  port: 9965
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    hostname: localhost    

logging:
  file:
    name: serverout.log 
    
spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comments/**
          filters:
            - name: CircuitBreaker
              args:
                name: COMMENT-SERVICE
                fallbackuri: forward:/commentServiceFallBack            
            
            
resilience4j:
    timelimiter:
        configs:
            default:
                timeoutDuration: 1000      